### ISSUE TITLE
Autorestart closes after trying to start

### ISSUE THREAD

**Issue by fo0b** [Sightem/Roblox-Autorestart#2]
After opening the autorestart executable, entering the delay, and selecting whether I'm using krnl or synapse, the program closes.  I've tried reinstalling krnl, and in turn the workspace, changing the cookies, and reinstalling the program. No change.

**Comment by Sightem** [comment]
yea known issue, i have to rewrite it basically from ground up

**Comment by Sightem** [comment]
this is now fixed bb5c128e61d040376919b28e366d81566dfcb711
